config/routes.rb
Rails.application.routes.draw do

  get 'course_connections/index'
  get 'profile' => "home#profile"
  get 'welcome' => "home#welcome"
  get 'all_students' => "home#get_students"
  delete 'course_connections' => "course_connections#destroy"

  devise_for :users
  resources :courses do
    get "students" => "course_connections#index"
  end

  resources :course_connections, only: [:create, :index]
  root 'home#welcome'
  get "index" => "home#index"

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_many :student_connections, class_name: 'CourseConnection', foreign_key: 'course_id', dependent: :destroy

  has_many :students, through: :student_connections, source: :student
end

app/models/course_connection.rb
class CourseConnection < ActiveRecord::Base
  belongs_to :student, class_name: "User"
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses
  has_many :course_connections, class_name: 'CourseConnection', foreign_key: 'student_id', dependent: :destroy

  has_many :assisted_courses, through: :course_connections, source: :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
  end
end

app/controllers/course_connections_controller.rb
class CourseConnectionsController < ApplicationController
  respond_to :json

  def index
    course = Course.find(params[:course_id])
    @students = course.students
    respond_to do |format|
      format.json
    end
  end

  def create
    @course_connection = CourseConnection.create!(course_connection_params)
    respond_to do |format|
      format.json
    end
  end

  def destroy
    course_conn = CourseConnection.find_by_course_id_and_student_id(params[:course_id], params[:student_id])
    if(course_conn.destroy)
			render json: course_conn, status: :ok
    end
  end

  private

	def course_connection_params
		params.require(:course_connection).permit(:student_id, :course_id)
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	respond_to :json

	def index
		@courses = current_user.courses
		render json: @courses
	end

	def show
		@course = Course.find(params[:id])
		render json: @course
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)
		@course.user = current_user
		p "*" * 100
		p params
		if @course.save
			redirect_to root_path
		end
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		course = Course.find(params[:id])
    if(course.update_attributes(course_params))
			render json: course, status: :ok
    end
	end

	def destroy
		course = Course.find(params[:id])
    if(course.destroy)
			render json: course, status: :ok
    end
	end

	private

	def course_params
		params.require(:course).permit(:title, :description, :category)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout false, only: [:profile, :index]

  def welcome
  end

  def index
    @courses = current_user.courses.order(:title) if user_signed_in?
    @assisted_courses = current_user.assisted_courses if user_signed_in?
    respond_to do |format|
      format.html # index.html.haml
      format.json
    end
  end

  def profile
    @profile = current_user
  end

  def get_students
    @students = User.where.not(id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_connections_helper.rb
module CourseConnectionsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/course_connections/index.html.haml
%h1 CourseConnections#index
%p Find me in app/views/course_connections/index.html.haml

app/views/courses/create.html.haml
%h1 Courses#create
%p Find me in app/views/courses/create.html.haml

app/views/courses/destroy.html.haml
%h1 Courses#destroy
%p Find me in app/views/courses/destroy.html.haml

app/views/courses/edit.html.haml
= form_for @course, :html => {:class => "login-form form-horizontal"} do |f|
  %fieldset
    %legend Course Details
    .form-group
      = f.label :title, :class => "control-label"
      = f.text_field :title, :class => "form-control", autofocus: true
    .form-group
      = f.label :description, :class => "control-label"
      = f.text_area :description, :class => "form-control", :rows => "3"
      %span.help-block Describe the course in 500 characters or less.
    .form-group
      %label.col-lg-2.control-label{:for => "select"} Category
      .col-lg-10
        = f.select(:category, ["Computers", "Math", "Science", "Utilities"], { include_blank: false }, :class => "form-control")
        /= select_tag(:category, options_for_select(["Computers", "Math"], "Computers"), :class => "form-control")
    .form-group
      .col-lg-10.col-lg-offset-2
        %button.btn.btn-default{:type => "reset"} Cancel
        %button.btn.btn-primary{:type => "submit"} Create

app/views/courses/index.html.haml
%h1 Courses#index
%p Find me in app/views/courses/index.html.haml

app/views/courses/new.html.haml
= form_for @course, :html => {:class => "login-form form-horizontal"} do |f|
  %fieldset
    %legend Course Details
    .form-group
      = f.label :title, :class => "control-label"
      = f.text_field :title, :class => "form-control", autofocus: true
    .form-group
      = f.label :description, :class => "control-label"
      = f.text_area :description, :class => "form-control", :rows => "3"
      %span.help-block Describe the course in 500 characters or less.
    .form-group
      %label.col-lg-2.control-label{:for => "select"} Category
      .col-lg-10
        = f.select(:category, ["Computers", "Math", "Science", "Utilities"], { include_blank: false }, :class => "form-control")
        /= select_tag(:category, options_for_select(["Computers", "Math"], "Computers"), :class => "form-control")
    .form-group
      .col-lg-10.col-lg-offset-2
        %button.btn.btn-default{:type => "reset"} Cancel
        %button.btn.btn-primary{:type => "submit"} Create

app/views/courses/show.html.haml
%h1 Courses#show
%p Find me in app/views/courses/show.html.haml

app/views/courses/update.html.haml
%h1 Courses#update
%p Find me in app/views/courses/update.html.haml

app/views/home/index.html.haml
.container
  = link_to "Log", "", "ng-click" => "addAlert()"
  - if user_signed_in?
    = link_to "New Course", new_course_path

    %h3 My Courses
    %h6
      //Order by:
      //= link_to "Created At", "", "ng-click" => "setOrder('-created_at')","ng-model" => "order"
      // \/
      //= link_to "Title", "", "ng-click" => "setOrder('title')", "ng-model" => "order"
    .panel.panel-default{"ng-repeat" => "course in courses", "ng-controller" => "CourseConnectionsCtrl as conn"}
      .panel-heading{"ng-hide" => "getEditing() && getSelected(course)"}
        %button.btn.btn-info.btn-sm
          {{course.title}}
        %button.btn.btn-default.btn-sm{"ng-click" => "setSelected(course);", "ng-hide" => "getSelected(course)", :class => "description_link"}
          Description
          %span.glyphicon.glyphicon-chevron-down
        %button.btn.btn-default.btn-sm{"ng-click" => "setSelected(null)", "ng-show" => "getSelected(course)", :class => "description_link"}
          Description
          %span.glyphicon.glyphicon-chevron-up
        %button.btn.btn-warning.btn-sm{"ng-click" => "setSelected(course); setEditing(true); $event.stopPropagation(); setOldTitle(course.title)"}
          %span.glyphicon.glyphicon-pencil
        %button.btn.btn-danger.btn-sm{"ng-click" => "delete(course, $index); $event.stopPropagation();"}
          %span.glyphicon.glyphicon-trash
      .panel-heading{"ng-show" => "getEditing() && getSelected(course)"}
        %form{ "ng-submit" => "update(course, $index); $event.stopPropagation();", "ng-show" => "getEditing() && getSelected(course)", :style => "position: relative; display: inline"}
          %input{:required => true, "ng-model" => "course.title", :class => "form-control input-sm", :style => "width: 400px; position: relative; display: inline", "ng-blur" => "cancelEditing(course)" }
          %input{:type => "submit", :value => "Update", :class => "btn btn-warning btn-sm"}
        %button.btn.btn-info.btn-sm{"ng-click" => "setEditing(false); cancelEditing(course)", "ng-show" => "getEditing() && getSelected(course)", :style => "position: relative; display: inline"}
          Cancel
      .panel-body{"ng-show" => "getSelected(course)"}
        {{course.description}}
      .panel-footer
        %button.btn.btn-default.btn-sm{"data-placement" => "top", "data-toggle" => "tooltip", :title => "Number of students", :type => "button",
                                       "ng-click" => 'getStudents(course); showStudents = !showStudents;'}
          %span.glyphicon.glyphicon-refresh.glyphicon-refresh-animate{"ng-show" => "loading"}
          %span.glyphicon.glyphicon-user{"ng-hide" => "loading"}
          %span.badge
            {{course.students_number}}
      .panel-body{"ng-show" => "showStudents"}
        %table.table.table-striped.table-hover{"ng-hide" => "canEdit(course)"}
          %thead
            %tr
              %th #
              %th First Name
              %th Last Name
              %th Email
              %th ACTIONS
          %tbody
            %tr{"ng-repeat" => "student in students"}
              %td {{$index + 1}}
              %td
                {{student.first_name}}
              %td
                {{student.last_name}}
              %td
                {{student.email}}
              %td
                %button.btn.btn-danger.btn-xs{"ng-click" => "deleteStudent(student, course, $index)"}
                  Delete

        %a.btn.btn-sm.btn-default.btn-lg.btn-block{:href => "", "ng-click" => "addStudent = true", "ng-hide" => "addStudent"}
          %span.glyphicon.glyphicon-plus
          Add Student
        %a.btn.btn-sm.btn-default.btn-lg.btn-block{:href => "", "ng-click" => "addStudent = false; addStudent = false", "ng-show" => "addStudent"}
          %span.glyphicon.glyphicon-plus
          Cancel
        %input.form-control.input-sm{:type => "text", :placeholder => "Email", "ng-model" => "query.email", "ng-show" => "addStudent"}
        %table.table.table-striped.table-hover{"ng-show" => "addStudent && query.email.length > 0 && Course.FilteredStudents.length > 0"}
          %thead
            %tr
              %th #
              %th First Name
              %th Last Name
              %th Email
              %th ACTIONS
          %tbody
            %tr{"ng-repeat" => "student in Course.FilteredStudents = (Course.AllStudentss | filter: query | limitTo: 10)"}
              %td {{$index + 1}}
              %td
                {{student.first_name}}
              %td
                {{student.last_name}}
              %td
                {{student.email}}
              %td
                %button.btn.btn-success.btn-xs{"ng-click" => "addStudent(student, course, $index)"}
                  Add

    %h3 Courses I am subscribed to
    %h6
      //Order by:
      //= link_to "Created At", "", "ng-click" => "assisted_order = '-created_at'","ng-model" => "assisted_order"
      //\/
      //= link_to "Title", "", "ng-click" => "assisted_order = 'title'", "ng-model" => "assisted_order"
    .panel.panel-default{"ng-repeat" => "course in assisted_courses", "ng-click" => "select(course)"}
      .panel-heading{"ng-hide" => "getEditing() && getSelected(course)"}
        {{course.title}}
        = link_to "Edit name", "", "ng-click" => "setSelected(course); setEditing(true); $event.stopPropagation();", "ng-show" => "canEdit(course)"
      %form{ "ng-submit" => "update(course); $event.stopPropagation();", "ng-show" => "getEditing()  && getSelected(course)", :style => "position: relative; display: inline"}
        %input{:required => true, "ng-model" => "course.title", :class => "form-control input-sm", :style => "width: 400px; position: relative; display: inline" }
        %input{:type => "submit", :value => "Update", :class => "btn btn-primary btn-xs"}

      .panel-body{"ng-show" => "getSelected(course)"}
        {{course.description}}
        {{course.students_number}}
  %strong
    /{{orden}}

app/views/home/profile.html.haml
.row.profile
  .col-md-3
    .profile-sidebar
      / SIDEBAR USERPIC
      .profile-userpic
        %img.img-responsive{:alt => "", :src => "http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg"}/
      / END SIDEBAR USERPIC
      / SIDEBAR USER TITLE
      .profile-usertitle
        .profile-usertitle-name
          = "#{@profile.first_name} #{@profile.last_name}"
        .profile-usertitle-job
          Tutor
      / END SIDEBAR USER TITLE
      / SIDEBAR BUTTONS
      //.profile-userbuttons
      //  %button.btn.btn-success.btn-sm{:type => "button"} Follow
      //  %button.btn.btn-danger.btn-sm{:type => "button"} Message
      / END SIDEBAR BUTTONS
      / SIDEBAR MENU
      .profile-usermenu
        %ul.nav
          %li.active
            %a{:href => ""}
              %i.glyphicon.glyphicon-home
              Overview
          %li
            %a{:href => ""}
              %i.glyphicon.glyphicon-user
              Account Settings
          %li
            %a{:href => "", :target => "_blank"}
              %i.glyphicon.glyphicon-ok
              Tasks
          %li
            %a{:href => ""}
              %i.glyphicon.glyphicon-flag
              Help
      / END MENU
  .col-md-9
    .profile-content
      To manage your courses, go to the
      = link_to "Dashboard","", 'ng-click' => 'changeView("/"); activeWindow();', :Class => "description_link"
      by clicking on the top bar link.
%center
%br/
%br/

app/views/home/welcome.html.haml
%div{"ng-view" => ""}

app/views/layouts/application.html.haml
!!!
%html{"ng-app" => "eduapp"}
  %head
    %title EducationPlatform
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{"ng-controller" => "SchoolController as school"}
    %nav.navbar.navbar-default
      .container
        .container-fluid
          .navbar-header
            %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to "", :class => "navbar-brand", 'ng-click' => 'changeView("/")' do
              Education Platform
              %span.badge alpha
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li{"ng-class" => "dashboard_style"}
                = link_to "", 'ng-click' => 'changeView("/"); activeWindow();' do
                  Dashboard
                  %span.sr-only (current)
              - if user_signed_in?
                %li{"ng-class" => "profile_style"}
                  = link_to current_user.first_name, '', 'ng-click' => 'changeView("/profile"); activeWindow();'
            %ul.nav.navbar-nav.navbar-right
              %li
                - if user_signed_in?
                  = link_to("Sign out", destroy_user_session_path, :method => :delete)
                - else
                  = link_to "#{I18n.t 'sign_in'}", new_user_session_path
    .container
      = yield